name: 'autoblack'
author: 'Jonathan Medwig'
description: 'Automatically formats Python code to conform to the Black  style guide.'
inputs:
  args:
    description: 'Arguments to pass to Black'
    required: true
    default: '--help'
outputs:
  exit-code:
    description: 'The exit code output by Black'
runs:
  using: 'docker'
  image: 'docker://medwig/autoblack'
  args:
    - ${{ inputs.args }}
branding:
  icon: 'code'  
  color: 'blue'
