# Deletes the branch after it merges
name: branch-cleanup
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  cleanup-branch:
    name: on pull request merge, delete the branch
    runs-on: ubuntu-latest
    steps:
    - uses: jessfraz/branch-cleanup-action@master
